# Generated by Django 5.2.1 on 2026-08-28 01:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(db_index=True, verbose_name='ID du Club')),
                ('label', models.CharField(max_length=50, verbose_name='Libellé (ex: Exercice 2025-2026)')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('closed', 'Clôturé'), ('archived', 'Archivé')], default='open', max_length=10)),
            ],
            options={
                'verbose_name': 'Exercice Comptable',
                'verbose_name_plural': 'Exercices Comptables',
                'db_table': 'finance_fiscal_years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AccountPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(db_index=True, verbose_name='ID du Club')),
                ('code', models.CharField(max_length=20, verbose_name='Code du compte (ex: 4120, 7060)')),
                ('label', models.CharField(max_length=150, verbose_name='Libellé du compte')),
                ('account_type', models.CharField(choices=[('asset', 'Actif (Asset)'), ('liability', 'Passif (Liability)'), ('equity', 'Capitaux propres (Equity)'), ('revenue', 'Produit (Revenue)'), ('expense', 'Charge (Expense)')], max_length=15, verbose_name='Type IAS/IFRS')),
                ('parent_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Code compte parent (hiérarchie)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Compte (Plan Comptable)',
                'verbose_name_plural': 'Plan Comptable',
                'db_table': 'finance_account_plan',
                'ordering': ['code'],
                'unique_together': {('club_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(db_index=True, verbose_name='ID du Club')),
                ('journal', models.CharField(choices=[('ACH', 'Achats'), ('VTE', 'Ventes'), ('BNQ', 'Banque'), ('OD', 'Opérations Diverses'), ('SAL', 'Salaires'), ('IMM', 'Immobilisations')], max_length=3, verbose_name='Journal')),
                ('entry_date', models.DateField(verbose_name='Date comptable')),
                ('reference', models.CharField(max_length=50, verbose_name='Référence pièce (n° facture, virement…)')),
                ('label', models.CharField(max_length=200, verbose_name="Libellé de l'écriture")),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Débit (€)')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Crédit (€)')),
                ('currency_code', models.CharField(default='EUR', max_length=3, verbose_name='Code devise ISO 4217 (EUR, USD, GBP…)')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=10, verbose_name='Taux de change vers EUR')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Écriture validée (non modifiable)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.accountplan', verbose_name='Compte')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.fiscalyear', verbose_name='Exercice')),
            ],
            options={
                'verbose_name': 'Écriture Comptable',
                'verbose_name_plural': 'Écritures Comptables',
                'db_table': 'finance_journal_entries',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
    ]
