# Generated by Django 5.2.1 on 2026-09-12 02:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant1_id', models.BigIntegerField(db_index=True)),
                ('participant1_name', models.CharField(blank=True, default='', max_length=150)),
                ('participant2_id', models.BigIntegerField(db_index=True)),
                ('participant2_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'msg_conversations',
                'ordering': ['-last_message_at'],
                'unique_together': {('participant1_id', 'participant2_id')},
            },
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.BigIntegerField(db_index=True)),
                ('recipient_id', models.BigIntegerField(db_index=True)),
                ('content', models.TextField()),
                ('attachment_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('SENT', 'Envoyé'), ('READ', 'Lu')], default='SENT', max_length=10)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='direct_messages.conversation')),
            ],
            options={
                'db_table': 'msg_direct_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
