# Generated by Django 5.2.1 on 2026-09-12 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.BigIntegerField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('channel_type', models.CharField(choices=[('PUBLIC', 'Salon Public'), ('PRIVATE', 'Salon Privé'), ('TEAM', "Salon d'Équipe")], default='PUBLIC', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('creator_id', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'msg_chat_channels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChannelMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.BigIntegerField(db_index=True)),
                ('sender_name', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('attachment_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatchannel')),
            ],
            options={
                'db_table': 'msg_channel_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('user_name', models.CharField(blank=True, default='', max_length=150)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur du Salon'), ('MEMBER', 'Membre')], default='MEMBER', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chat.chatchannel')),
            ],
            options={
                'db_table': 'msg_channel_memberships',
                'unique_together': {('channel', 'user_id')},
            },
        ),
    ]
