# Generated by Django 5.2.1 on 2026-08-24 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('SUPER_ADMIN', 'Président / Super Administrateur'), ('CLUB_ADMIN', 'Administrateur du club'), ('TREASURER', 'Trésorier / Comptable'), ('COACH', 'Directeur Sportif / Entraîneur'), ('MEDICAL_STAFF', 'Médecin / Kinésithérapeute'), ('LOGISTICS', 'Responsable Matériel & Logistique'), ('MEMBER', 'Joueur / Adhérent / Parent')], help_text="Identifiant unique utilisé dans le code (ex: 'COACH')", max_length=30, unique=True, verbose_name='Code du rôle')),
                ('name', models.CharField(max_length=100, verbose_name='Nom affiché')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description des droits')),
                ('is_system_role', models.BooleanField(default=True, help_text='Les rôles système sont créés automatiquement et ne peuvent pas être supprimés.', verbose_name='Rôle système')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'db_table': 'auth_roles',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='UserClubRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'attribution")),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Attribué par')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='club.club', verbose_name='Club')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='rbac.role', verbose_name='Rôle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_roles', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Rôle utilisateur (club)',
                'verbose_name_plural': 'Rôles utilisateurs (club)',
                'db_table': 'auth_user_club_roles',
                'unique_together': {('user', 'club', 'role')},
            },
        ),
    ]
