# Generated by Django 5.2.1 on 2026-08-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Président / Super Administrateur'), ('CLUB_ADMIN', 'Administrateur du club'), ('TREASURER', 'Trésorier / Comptable'), ('COACH', 'Directeur Sportif / Entraîneur'), ('MEDICAL_STAFF', 'Médecin / Kinésithérapeute'), ('LOGISTICS', 'Responsable Matériel & Logistique'), ('MARKETING', 'Responsable Communication & Marketing'), ('MEMBER', 'Joueur / Adhérent / Parent')], help_text="Identifiant unique utilisé dans le code (ex: 'COACH')", max_length=30, unique=True, verbose_name='Code du rôle'),
        ),
    ]
