# Generated by Django 5.2.1 on 2026-08-28 01:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(db_index=True, verbose_name='ID du Club')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du compte (ex: Compte Courant Société Générale)')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Banque')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=11, verbose_name='BIC / SWIFT')),
                ('currency_code', models.CharField(default='EUR', max_length=3, verbose_name='Devise ISO 4217')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Solde actuel')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Compte Bancaire',
                'verbose_name_plural': 'Comptes Bancaires',
                'db_table': 'finance_bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(verbose_name='Date de valeur')),
                ('value_date', models.DateField(verbose_name='Date comptable')),
                ('label', models.CharField(max_length=200, verbose_name='Libellé du relevé bancaire')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence banque')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('direction', models.CharField(choices=[('credit', 'Crédit (+) — Entrée de trésorerie'), ('debit', 'Débit (-) — Sortie de trésorerie')], max_length=6)),
                ('category', models.CharField(choices=[('operating', "Activités d'exploitation (IAS 7)"), ('investing', "Activités d'investissement (IAS 7)"), ('financing', 'Activités de financement (IAS 7)')], default='operating', max_length=12, verbose_name='Catégorie IAS 7')),
                ('status', models.CharField(choices=[('pending', 'Non rapproché'), ('reconciled', 'Rapproché'), ('disputed', 'Contesté')], default='pending', max_length=12)),
                ('journal_entry_id', models.IntegerField(blank=True, null=True, verbose_name='ID Écriture comptable rapprochée (ledger)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.bankaccount', verbose_name='Compte')),
            ],
            options={
                'verbose_name': 'Transaction Bancaire',
                'verbose_name_plural': 'Transactions Bancaires',
                'db_table': 'finance_bank_transactions',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
