# Generated by Django 5.2.1 on 2026-08-28 01:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(db_index=True, verbose_name='ID du Club')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture (ex: FAC-2026-001)')),
                ('client_name', models.CharField(max_length=150, verbose_name='Nom du client')),
                ('client_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email client')),
                ('client_address', models.TextField(blank=True, default='', verbose_name='Adresse de facturation')),
                ('issue_date', models.DateField(verbose_name="Date d'émission")),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Émise'), ('paid', 'Payée'), ('overdue', 'En retard'), ('cancelled', 'Annulée'), ('credited', 'Avoirs émis')], default='draft', max_length=10)),
                ('amount_excl_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant HT')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='Taux TVA (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant TVA')),
                ('amount_incl_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant TTC')),
                ('currency_code', models.CharField(default='EUR', max_length=3, verbose_name='Devise ISO 4217')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Mentions légales & Remarques')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'db_table': 'finance_invoices',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(db_index=True, verbose_name='ID du Club')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence (ex: DEVIS-2026-001)')),
                ('client_name', models.CharField(max_length=150, verbose_name='Nom du client')),
                ('client_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email du client')),
                ('issue_date', models.DateField(verbose_name="Date d'émission")),
                ('validity_date', models.DateField(verbose_name='Date de validité')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('accepted', 'Accepté'), ('refused', 'Refusé'), ('expired', 'Expiré')], default='draft', max_length=10)),
                ('amount_excl_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant HT')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='Taux TVA (%)')),
                ('amount_incl_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant TTC')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Conditions & Remarques')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'db_table': 'finance_quotes',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description de la prestation')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire HT')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total HT')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoicing.invoice', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Ligne de Facture',
                'db_table': 'finance_invoice_items',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='quote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='invoicing.quote', verbose_name="Devis d'origine"),
        ),
    ]
