# Generated by Django 5.2.1 on 2026-09-04 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubWebsiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(db_index=True, unique=True, verbose_name='ID du Club')),
                ('club_name', models.CharField(max_length=150, verbose_name='Nom du club')),
                ('subdomain', models.SlugField(help_text='Sera utilisé comme https://[subdomain].gesport.com', max_length=80, unique=True, verbose_name='Sous-domaine')),
                ('logo_url', models.URLField(blank=True, default='', verbose_name='URL du logo')),
                ('banner_url', models.URLField(blank=True, default='', verbose_name='URL de la bannière')),
                ('primary_color', models.CharField(default='#1E3A5F', max_length=7, verbose_name='Couleur primaire (hex)')),
                ('secondary_color', models.CharField(default='#F5A623', max_length=7, verbose_name='Couleur secondaire (hex)')),
                ('meta_title', models.CharField(blank=True, default='', max_length=200, verbose_name='Meta title (SEO)')),
                ('meta_description', models.TextField(blank=True, default='', verbose_name='Meta description (SEO)')),
                ('facebook_url', models.URLField(blank=True, default='', verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, default='', verbose_name='Instagram')),
                ('twitter_url', models.URLField(blank=True, default='', verbose_name='X / Twitter')),
                ('youtube_url', models.URLField(blank=True, default='', verbose_name='YouTube')),
                ('is_published', models.BooleanField(default=False, verbose_name='Site publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Site Web',
                'verbose_name_plural': 'Configurations Sites Web',
                'db_table': 'cms_club_website_config',
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(db_index=True, verbose_name='ID du Club')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Vidéo'), ('DOCUMENT', 'Document')], default='IMAGE', max_length=20)),
                ('file', models.FileField(upload_to='media_library/%Y/%m/', verbose_name='Fichier')),
                ('file_url', models.URLField(blank=True, default='', verbose_name='URL externe (optionnel)')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Taille (octets)')),
                ('mime_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Type MIME')),
                ('category', models.CharField(blank=True, default='', max_length=80, verbose_name='Catégorie')),
                ('alt_text', models.CharField(blank=True, default='', max_length=200, verbose_name='Texte alternatif')),
                ('uploaded_by_id', models.IntegerField(blank=True, null=True, verbose_name='ID Utilisateur (IAM)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médias',
                'db_table': 'cms_media_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(db_index=True, verbose_name='ID du Club')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(max_length=120, verbose_name='Slug URL')),
            ],
            options={
                'verbose_name': "Catégorie d'article",
                'verbose_name_plural': "Catégories d'articles",
                'db_table': 'cms_article_categories',
                'unique_together': {('club_id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(db_index=True, verbose_name='ID du Club')),
                ('name', models.CharField(max_length=60, verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'cms_article_tags',
                'unique_together': {('club_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(db_index=True, verbose_name='ID du Club')),
                ('title', models.CharField(max_length=250, verbose_name="Titre de l'article")),
                ('slug', models.SlugField(max_length=280, verbose_name='Slug URL')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Résumé / Chapeau')),
                ('content', models.TextField(verbose_name='Contenu (HTML / RichText)')),
                ('cover_image_url', models.URLField(blank=True, default='', verbose_name='Image de couverture (URL)')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('author_id', models.IntegerField(blank=True, null=True, verbose_name='ID Auteur (IAM)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.articlecategory', verbose_name='Catégorie')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='news.articletag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'db_table': 'cms_articles',
                'ordering': ['-published_at', '-created_at'],
                'unique_together': {('club_id', 'slug')},
            },
        ),
    ]
