# Generated by Django 5.2.1 on 2026-08-28 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VaultDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('file_path_or_s3_key', models.CharField(max_length=512)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=100)),
                ('sha256_hash', models.CharField(blank=True, default='', max_length=64)),
                ('confidentiality_level', models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNAL', 'Interne'), ('CONFIDENTIAL', 'Confidentiel'), ('RESTRICTED', 'Restreint')], default='CONFIDENTIAL', max_length=20)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('encryption_algorithm', models.CharField(default='AES-256', max_length=50)),
                ('uploaded_by', models.CharField(blank=True, default='system', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_by', models.CharField(default='anonymous', max_length=150)),
                ('access_type', models.CharField(choices=[('READ', 'Lecture'), ('DOWNLOAD', 'Téléchargement'), ('PRESIGNED_URL_GENERATED', 'URL Pré-signée')], default='READ', max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='vault.vaultdocument')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
