# Generated by Django 5.2.1 on 2026-09-04 00:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.BigIntegerField(db_index=True, help_text='ID du club organisateur')),
                ('title', models.CharField(help_text="Titre de l'événement", max_length=255)),
                ('slug', models.SlugField(help_text='Slug URL unique pour le club', max_length=255)),
                ('event_type', models.CharField(choices=[('MATCH', 'Match de championnat / coupe'), ('STAGE', 'Stage de vacances / perfectionnement'), ('GALA', 'Soirée de Gala'), ('TOURNOI', 'Tournoi'), ('AUTRE', 'Autre événement')], default='MATCH', max_length=50)),
                ('description', models.TextField(blank=True, default='', help_text="Description de l'événement")),
                ('location', models.CharField(help_text='Lieu / Stade / Gymnase', max_length=255)),
                ('start_date', models.DateTimeField(help_text='Date et heure de début')),
                ('end_date', models.DateTimeField(blank=True, help_text='Date et heure de fin', null=True)),
                ('cover_image_url', models.URLField(blank=True, help_text='Affiche / Image de couverture', max_length=1000, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('OPEN', 'Billetterie Ouverte'), ('CLOSED', 'Billetterie Fermée'), ('CANCELLED', 'Événement Annulé')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Événement Billetterie',
                'verbose_name_plural': 'Événements Billetterie',
                'db_table': 'cms_ticket_event',
                'ordering': ['-start_date'],
                'unique_together': {('club_id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la catégorie (ex: Tribune VIP, Standard, Enfant)', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, help_text='Prix unitaire du billet', max_digits=10)),
                ('currency', models.CharField(default='XAF', help_text='Devise (XAF, EUR, USD)', max_length=10)),
                ('total_capacity', models.PositiveIntegerField(help_text='Quota total de billets disponibles pour cette catégorie')),
                ('sold_count', models.PositiveIntegerField(default=0, help_text='Nombre de billets déjà vendus/réservés')),
                ('is_active', models.BooleanField(default=True, help_text='Catégorie ouverte à la vente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='ticketing.ticketevent')),
            ],
            options={
                'verbose_name': 'Catégorie de billet',
                'verbose_name_plural': 'Catégories de billets',
                'db_table': 'cms_ticket_category',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(db_index=True, default=uuid.uuid4, help_text='Code unique alphanumérique / UUID du billet', max_length=64, unique=True)),
                ('buyer_name', models.CharField(help_text="Nom complet de l'acheteur/détenteur", max_length=255)),
                ('buyer_email', models.EmailField(help_text='Adresse email du destinataire du billet', max_length=254)),
                ('buyer_phone', models.CharField(blank=True, default='', help_text='Téléphone du détenteur', max_length=50)),
                ('price_paid', models.DecimalField(decimal_places=2, help_text='Montant payé pour le billet', max_digits=10)),
                ('status', models.CharField(choices=[('VALID', 'Valide'), ('USED', "Utilisé (Scanné à l'entrée)"), ('CANCELLED', 'Annulé / Remboursé')], default='VALID', max_length=20)),
                ('qr_code_data', models.TextField(blank=True, default='', help_text='Signature HMAC / Données encodées dans le QR code')),
                ('checked_in_at', models.DateTimeField(blank=True, help_text="Horodatage du scan à l'entrée", null=True)),
                ('checked_in_by_id', models.BigIntegerField(blank=True, help_text='ID du contrôleur/agent qui a scanné le billet', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ticketing.ticketcategory')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ticketing.ticketevent')),
            ],
            options={
                'verbose_name': 'Billet',
                'verbose_name_plural': 'Billets',
                'db_table': 'cms_ticket',
                'ordering': ['-created_at'],
            },
        ),
    ]
