# Generated by Django 5.2.1 on 2026-09-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.BigIntegerField(db_index=True)),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('SYSTEM', 'Système'), ('CHAT', 'Chat'), ('SPORT', 'Sport'), ('FINANCE', 'Finance')], default='SYSTEM', max_length=20)),
                ('level', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Avertissement'), ('URGENT', 'Urgent')], default='INFO', max_length=10)),
                ('status', models.CharField(choices=[('UNREAD', 'Non lu'), ('READ', 'Lu')], default='UNREAD', max_length=10)),
                ('action_url', models.URLField(blank=True, max_length=500, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'msg_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
