# Generated by Django 5.2.1 on 2026-08-28 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('brand_model', models.CharField(max_length=255)),
                ('seating_capacity', models.PositiveIntegerField(default=9)),
                ('fuel_type', models.CharField(choices=[('DIESEL', 'Gazole / Diesel'), ('GASOLINE', 'Essence'), ('ELECTRIC', 'Électrique'), ('HYBRID', 'Hybride')], default='DIESEL', max_length=20)),
                ('current_mileage', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('RESERVED', 'Réservé'), ('IN_MAINTENANCE', 'En maintenance'), ('OUT_OF_SERVICE', 'Hors service')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=255)),
                ('driver_email', models.EmailField(max_length=254)),
                ('purpose', models.CharField(help_text="Motif du déplacement (ex: Match à l'extérieur U17)", max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('CANCELLED', 'Annulée'), ('COMPLETED', 'Terminée')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
