# Generated by Django 5.2.1 on 2026-09-04 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPrintOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.BigIntegerField(db_index=True, help_text='ID du club propriétaire')),
                ('name', models.CharField(help_text="Nom de l'option (ex: Flocage Officiel Ligue 1)", max_length=100)),
                ('print_type', models.CharField(choices=[('NAME_NUMBER', 'Nom + Numéro'), ('NUMBER_ONLY', 'Numéro Seul'), ('NAME_ONLY', 'Nom Seul'), ('PATCH', 'Écusson / Logo')], default='NAME_NUMBER', max_length=50)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Prix additionnel du flocage', max_digits=10)),
                ('allowed_locations', models.JSONField(blank=True, default=list, help_text="Emplacements autorisés ex: ['BACK', 'CHEST']")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Option de flocage',
                'verbose_name_plural': 'Options de flocage',
                'db_table': 'shop_custom_print_options',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomPrintDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, default='', help_text='Nom à floquer', max_length=100)),
                ('custom_number', models.CharField(blank=True, default='', help_text='Numéro à floquer', max_length=20)),
                ('location', models.CharField(default='BACK', help_text='Emplacement (BACK, CHEST, SLEEVE)', max_length=50)),
                ('font_style', models.CharField(blank=True, default='STANDARD', max_length=50)),
                ('color', models.CharField(blank=True, default='WHITE', max_length=50)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_details', to='custom_prints.customprintoption')),
            ],
            options={
                'verbose_name': 'Détail de flocage',
                'verbose_name_plural': 'Détails de flocage',
                'db_table': 'shop_custom_print_details',
                'ordering': ['-created_at'],
            },
        ),
    ]
