# Generated by Django 5.2.1 on 2026-08-25 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=150, verbose_name='Établissement scolaire / Lycée')),
                ('grade_level', models.CharField(max_length=50, verbose_name='Classe / Niveau (ex: 3ème, Terminale)')),
                ('academic_gpa', models.FloatField(default=14.0, verbose_name='Moyenne générale (/20)')),
                ('tutor_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Nom du tuteur / Référent')),
                ('tutor_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone du tuteur')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Bilan comportemental & sportif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academy_profile', to='membres.member', verbose_name='Membre / Joueur')),
            ],
            options={
                'verbose_name': 'Élève Académie',
                'verbose_name_plural': 'Élèves Académie',
                'db_table': 'sport_academy_students',
            },
        ),
    ]
