# Generated by Django 5.2.1 on 2026-09-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academystudent',
            name='age',
            field=models.IntegerField(blank=True, default=16, null=True, verbose_name='Âge'),
        ),
        migrations.AddField(
            model_name='academystudent',
            name='parents_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Nom des parents / tuteurs légaux'),
        ),
        migrations.AddField(
            model_name='academystudent',
            name='school_support_needed',
            field=models.BooleanField(default=False, verbose_name='Soutien scolaire requis'),
        ),
        migrations.AlterField(
            model_name='academystudent',
            name='tutor_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nom du coach tuteur référent'),
        ),
    ]
