# Generated by Django 5.2.1 on 2026-08-24 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom officiel du club (ex: 'AS Saint-Germain Omnisports')", max_length=200, verbose_name='Nom du club')),
                ('slug', models.SlugField(blank=True, help_text='Identifiant unique dans les URLs. Généré automatiquement depuis le nom.', max_length=220, unique=True, verbose_name='Slug URL')),
                ('short_name', models.CharField(blank=True, default='', help_text="Ex: 'ASSG' ou 'USM'", max_length=50, verbose_name='Nom abrégé')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clubs/logos/', verbose_name='Logo')),
                ('primary_color', models.CharField(default='#1a56db', help_text='Ex: #1a56db', max_length=7, verbose_name='Couleur principale (hex)')),
                ('secondary_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Couleur secondaire (hex)')),
                ('address', models.CharField(blank=True, default='', max_length=300, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Code postal')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email du club')),
                ('website', models.URLField(blank=True, default='', verbose_name='Site web')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Club actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
                'db_table': 'auth_clubs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Ex: '2025-2026'", max_length=20, verbose_name='Nom de la saison')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('is_current', models.BooleanField(default=False, help_text="Une seule saison peut être 'en cours' par club.", verbose_name='Saison en cours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='club.club', verbose_name='Club')),
            ],
            options={
                'verbose_name': 'Saison sportive',
                'verbose_name_plural': 'Saisons sportives',
                'db_table': 'auth_seasons',
                'ordering': ['-start_date'],
                'unique_together': {('club', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserClubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text="Si False, l'utilisateur n'a plus accès aux données de ce club.", verbose_name='Adhésion active')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'adhésion")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='club.club', verbose_name='Club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Adhésion club',
                'verbose_name_plural': 'Adhésions club',
                'db_table': 'auth_user_club_memberships',
                'unique_together': {('user', 'club')},
            },
        ),
    ]
