# Generated by Django 5.2.1 on 2026-09-04 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.BigIntegerField(db_index=True, help_text='ID du club propriétaire du segment')),
                ('name', models.CharField(help_text="Nom du segment d'audience", max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text="Description des critères de l'audience")),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Filtres dynamiques (âge, équipe, rôle, etc.)')),
                ('estimated_size', models.PositiveIntegerField(default=0, help_text="Taille estimée de l'audience")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Segment d'audience",
                'verbose_name_plural': "Segments d'audience",
                'db_table': 'cms_audience_segment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.BigIntegerField(db_index=True, help_text='ID du club organisateur')),
                ('title', models.CharField(help_text='Titre / Nom interne de la campagne', max_length=255)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], default='EMAIL', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SCHEDULED', 'Planifiée'), ('SENDING', "En cours d'envoi"), ('SENT', 'Envoyée'), ('FAILED', 'Échouée'), ('CANCELLED', 'Annulée')], default='DRAFT', max_length=20)),
                ('subject', models.CharField(blank=True, default='', help_text='Objet (pour les e-mails)', max_length=255)),
                ('content', models.TextField(help_text='Contenu du message (Texte, HTML ou Markdown)')),
                ('media_url', models.URLField(blank=True, help_text='Média/Visuel joint (ex: image WhatsApp ou PJ email)', max_length=1000, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text="Date/heure de planification d'envoi", null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text="Date/heure réelle d'envoi", null=True)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('opened_count', models.PositiveIntegerField(default=0)),
                ('clicked_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_by_id', models.BigIntegerField(blank=True, help_text="ID de l'utilisateur créateur", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segment', models.ForeignKey(blank=True, help_text="Segment d'audience ciblé", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='campaigns.audiencesegment')),
            ],
            options={
                'verbose_name': 'Campagne marketing',
                'verbose_name_plural': 'Campagnes marketing',
                'db_table': 'cms_campaign',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipientLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_contact', models.CharField(help_text='Adresse Email ou numéro de téléphone', max_length=255)),
                ('recipient_id', models.BigIntegerField(blank=True, help_text='ID du licencié/membre si disponible', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyé'), ('DELIVERED', 'Délivré'), ('FAILED', 'Échec')], default='PENDING', max_length=20)),
                ('external_message_id', models.CharField(blank=True, help_text='ID du message retourné par Brevo/Geskap', max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, help_text="Raison de l'échec si statut FAILED", null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_logs', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Log destinataire campagne',
                'verbose_name_plural': 'Logs destinataires campagne',
                'db_table': 'cms_campaign_recipient_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
