# Generated by Django 5.2.1 on 2026-09-04 23:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_prints', '0001_initial'),
        ('inventory_variants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='ID de session anonyme ou jeton panier', max_length=100)),
                ('user_id', models.BigIntegerField(blank=True, help_text="ID de l'utilisateur authentifié (IAM)", null=True)),
                ('club_id', models.BigIntegerField(db_index=True, help_text='ID du club de la boutique')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
                'db_table': 'shop_carts',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, default=uuid.uuid4, help_text='Numéro unique de commande (ex: ORD-2026-XXXX)', max_length=64, unique=True)),
                ('club_id', models.BigIntegerField(db_index=True, help_text='ID du club bénéficiaire')),
                ('user_id', models.BigIntegerField(blank=True, help_text="ID de l'acheteur (IAM) si connecté", null=True)),
                ('customer_name', models.CharField(help_text="Nom complet de l'acheteur", max_length=255)),
                ('customer_email', models.EmailField(help_text="Email de l'acheteur", max_length=254)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=50)),
                ('shipping_address', models.TextField(help_text='Adresse postale complète de livraison')),
                ('status', models.CharField(choices=[('PENDING', 'En attente de paiement'), ('PAID', 'Payée'), ('PROCESSING', 'En cours de préparation'), ('SHIPPED', 'Expédiée'), ('DELIVERED', 'Livrée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Sous-total hors livraison', max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Frais de livraison', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Montant total TTC payé', max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'db_table': 'shop_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart')),
                ('print_detail', models.ForeignKey(blank=True, help_text='Flocage personnalisé optionnel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='custom_prints.customprintdetail')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='inventory_variants.productvariant')),
            ],
            options={
                'verbose_name': 'Article du panier',
                'verbose_name_plural': 'Articles du panier',
                'db_table': 'shop_cart_items',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text="Nom du produit sauvegardé à l'achat", max_length=255)),
                ('variant_sku', models.CharField(help_text='SKU de la variante', max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text="Prix unitaire à l'achat", max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total pour cette ligne', max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('print_detail', models.ForeignKey(blank=True, help_text='Détail du flocage associé à cet article', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='custom_prints.customprintdetail')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='inventory_variants.productvariant')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
                'db_table': 'shop_order_items',
            },
        ),
    ]
