# Generated by Django 5.2.1 on 2026-08-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(db_index=True, verbose_name='ID du Club')),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID Utilisateur IAM')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('sport_type', models.CharField(default='football', max_length=30, verbose_name='Sport principal')),
                ('category', models.CharField(choices=[('Baby/U9', 'Baby / U9'), ('U11', 'U11'), ('U13', 'U13'), ('U15', 'U15'), ('U18', 'U18'), ('Senior Régionale', 'Senior Régionale'), ('Senior Nationale', 'Senior Nationale'), ('Loisir / Masters', 'Loisir / Masters'), ('Pro Élite', 'Pro Élite')], default='Senior Régionale', max_length=40)),
                ('license_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Numéro de licence')),
                ('license_status', models.CharField(choices=[('Validée', 'Validée'), ('En attente', 'En attente'), ('Expirée', 'Expirée'), ('Paiement partiel', 'Paiement partiel')], default='En attente', max_length=30)),
                ('medical_cert_valid', models.BooleanField(default=False, verbose_name='Certificat médical valide')),
                ('medical_cert_date', models.DateField(blank=True, null=True, verbose_name='Date du certificat médical')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Adhérent',
                'verbose_name_plural': 'Adhérents',
                'db_table': 'sport_members',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
