# Generated by Django 5.2.1 on 2026-09-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cotisation_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant cotisation'),
        ),
        migrations.AddField(
            model_name='member',
            name='cotisation_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant payé'),
        ),
        migrations.AddField(
            model_name='member',
            name='daily_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Salaire journalier (prime d'entraînement)"),
        ),
        migrations.AddField(
            model_name='member',
            name='gross_monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire mensuel brut'),
        ),
        migrations.AddField(
            model_name='member',
            name='jersey_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numéro de maillot'),
        ),
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Poste principal'),
        ),
    ]
