# Generated by Django 5.2.1 on 2026-08-25 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_type', models.CharField(max_length=150, verbose_name='Type de blessure (ex: Entorse, Élongation)')),
                ('body_part', models.CharField(max_length=100, verbose_name='Partie du corps touchée (ex: Cheville droite)')),
                ('injury_date', models.DateField(verbose_name='Date de la blessure')),
                ('expected_return_date', models.DateField(blank=True, null=True, verbose_name='Date de retour estimée')),
                ('status', models.CharField(choices=[('En soins', 'En soins'), ('Réathlétisation', 'Réathlétisation'), ('Apte', 'Apte'), ('Indisponible', 'Indisponible')], default='En soins', max_length=30)),
                ('doctor_notes', models.TextField(blank=True, default='', verbose_name='Observations médecin / kiné')),
                ('return_clearance_certified', models.BooleanField(default=False, verbose_name='Autorisation de reprise validée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='membres.member', verbose_name='Joueur')),
            ],
            options={
                'verbose_name': 'Dossier Médical',
                'verbose_name_plural': 'Dossiers Médicaux',
                'db_table': 'sport_medical_records',
                'ordering': ['-injury_date'],
            },
        ),
    ]
