# Generated by Django 5.2.1 on 2026-08-28 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(db_index=True, verbose_name='ID du Club')),
                ('donor_type', models.CharField(choices=[('individual', 'Personne physique'), ('company', 'Personne morale / Entreprise')], default='individual', max_length=12)),
                ('first_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom / Raison sociale')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, default='', verbose_name='Adresse postale fiscale')),
                ('tax_id', models.CharField(blank=True, default='', max_length=50, verbose_name='Numéro fiscal / SIRET')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Donateur',
                'verbose_name_plural': 'Donateurs',
                'db_table': 'finance_donors',
            },
        ),
        migrations.CreateModel(
            name='TaxReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(db_index=True, verbose_name='ID du Club')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro du reçu (ex: CERFA-2026-0001)')),
                ('donation_date', models.DateField(verbose_name='Date du don')),
                ('donation_type', models.CharField(choices=[('money', 'Don en numéraire'), ('kind', 'Don en nature'), ('skills', 'Mécénat de compétences')], default='money', max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant du don')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='Objet du don (si en nature)')),
                ('status', models.CharField(choices=[('issued', 'Émis'), ('cancelled', 'Annulé'), ('reissued', 'Réémis (correction)')], default='issued', max_length=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='tax_receipts.donor', verbose_name='Donateur')),
            ],
            options={
                'verbose_name': 'Reçu Fiscal',
                'verbose_name_plural': 'Reçus Fiscaux',
                'db_table': 'finance_tax_receipts',
                'ordering': ['-issued_at'],
            },
        ),
    ]
