# Generated by Django 5.2.1 on 2026-08-25 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TacticalBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(db_index=True, verbose_name='ID du Club')),
                ('title', models.CharField(max_length=150, verbose_name='Titre du schéma')),
                ('sport_type', models.CharField(default='football', max_length=30, verbose_name='Sport')),
                ('system_name', models.CharField(default='4-3-3', max_length=50, verbose_name='Nom du système (ex: 4-3-3, 5-1)')),
                ('lineup_json', models.JSONField(default=dict, verbose_name='Positions des joueurs (JSON)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Consignes tactiques')),
                ('coach_id', models.IntegerField(blank=True, null=True, verbose_name='ID Coach IAM')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Schéma Tactique',
                'verbose_name_plural': 'Schémas Tactiques',
                'db_table': 'sport_tactical_boards',
            },
        ),
        migrations.CreateModel(
            name='TrainingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(db_index=True, verbose_name='ID du Club')),
                ('title', models.CharField(max_length=150, verbose_name="Titre de l'exercice")),
                ('sport_type', models.CharField(default='football', max_length=30, verbose_name='Sport')),
                ('category', models.CharField(default='Physique / Cardio', max_length=50, verbose_name='Catégorie')),
                ('duration_minutes', models.IntegerField(default=15, verbose_name='Durée (minutes)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description & Consignes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Exercice d'entraînement",
                'verbose_name_plural': "Exercices d'entraînement",
                'db_table': 'sport_training_exercises',
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre de la séance')),
                ('session_date', models.DateTimeField(verbose_name='Date et heure de la séance')),
                ('duration_minutes', models.IntegerField(default=90, verbose_name='Durée totale (minutes)')),
                ('attendance_count', models.IntegerField(default=0, verbose_name='Nombre de présents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercises', models.ManyToManyField(blank=True, related_name='sessions', to='tactics.trainingexercise', verbose_name='Exercices du programme')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='teams.team', verbose_name='Équipe')),
            ],
            options={
                'verbose_name': "Séance d'entraînement",
                'verbose_name_plural': "Séances d'entraînement",
                'db_table': 'sport_training_sessions',
                'ordering': ['-session_date'],
            },
        ),
    ]
