# Generated by Django 5.2.1 on 2026-09-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingexercise',
            name='diagram_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Données du schéma tactique'),
        ),
        migrations.AddField(
            model_name='trainingexercise',
            name='instructions_json',
            field=models.JSONField(blank=True, default=list, verbose_name='Instructions détaillées'),
        ),
        migrations.AddField(
            model_name='trainingexercise',
            name='intensity',
            field=models.CharField(default='Moyenne', max_length=30, verbose_name='Intensité'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='coach_feedback',
            field=models.TextField(blank=True, default='', verbose_name='Débrief / Feedback Coach'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='coach_name',
            field=models.CharField(default='Coach Principal', max_length=100, verbose_name='Entraîneur Responsable'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='end_time',
            field=models.CharField(default='21:00', max_length=20, verbose_name='Heure Fin'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='intensity',
            field=models.CharField(default='Moyenne', max_length=30, verbose_name='Intensité'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='start_time',
            field=models.CharField(default='19:00', max_length=20, verbose_name='Heure Début'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='theme',
            field=models.CharField(default='Perfectionnement Technique', max_length=200, verbose_name='Thème principal'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='total_summoned',
            field=models.IntegerField(default=14, verbose_name='Nombre total convoqués'),
        ),
        migrations.AlterField(
            model_name='tacticalboard',
            name='lineup_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='Positions des joueurs (JSON)'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='attendance_count',
            field=models.IntegerField(default=12, verbose_name='Nombre de présents'),
        ),
    ]
