# Generated by Django 5.2.1 on 2026-09-04 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('UNIQUE', 'Taille Unique')], default='M', max_length=20)),
                ('color', models.CharField(blank=True, default='', help_text='Couleur (ex: Bleu, Rouge)', max_length=50)),
                ('sku', models.CharField(db_index=True, help_text="Code SKU unique d'inventaire", max_length=100, unique=True)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Prix de vente si différent du prix de base du produit', max_digits=10, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Quantité actuellement disponible')),
                ('reorder_threshold', models.PositiveIntegerField(default=5, help_text="Seuil d'alerte de stock bas")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Variante de produit',
                'verbose_name_plural': 'Variantes de produits',
                'db_table': 'shop_product_variants',
                'ordering': ['size', 'color'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Variation de quantité (+ pour entrée, - pour sortie)')),
                ('movement_type', models.CharField(choices=[('ENTRY', 'Réapprovisionnement'), ('SALE', 'Vente / Commande'), ('ADJUSTMENT', 'Ajustement inventaire'), ('RETURN', 'Retour client')], default='ENTRY', max_length=20)),
                ('reason', models.CharField(blank=True, default='', help_text='Raison ou référence de commande', max_length=255)),
                ('author_id', models.BigIntegerField(blank=True, help_text="ID de l'utilisateur ayant fait l'ajustement", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory_variants.productvariant')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'db_table': 'shop_stock_movements',
                'ordering': ['-created_at'],
            },
        ),
    ]
