# Generated by Django 5.2.1 on 2026-08-28 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=255)),
                ('borrower_email', models.EmailField(max_length=254)),
                ('quantity_borrowed', models.PositiveIntegerField(default=1)),
                ('loan_date', models.DateField(auto_now_add=True)),
                ('expected_return_date', models.DateField()),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'En cours'), ('RETURNED', 'Restitué'), ('OVERDUE', 'En retard')], default='ACTIVE', max_length=20)),
                ('initial_condition_notes', models.TextField(blank=True, default='Bon état')),
                ('return_condition_notes', models.TextField(blank=True, default='')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='inventory.equipmentitem')),
            ],
            options={
                'ordering': ['-loan_date'],
            },
        ),
    ]
