# Generated by Django 5.2.1 on 2026-08-28 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(db_index=True, verbose_name='ID du Club')),
                ('company_name', models.CharField(max_length=150, verbose_name='Raison sociale / Nom entreprise')),
                ('sponsor_type', models.CharField(choices=[('corporate', 'Entreprise B2B / PME'), ('institutional', 'Institutionnel / Collectivité'), ('local_business', 'Commerce local'), ('patron', 'Mécène privé')], default='corporate', max_length=20)),
                ('siret', models.CharField(blank=True, default='', max_length=14, verbose_name='Numéro SIRET / ID Legal')),
                ('contact_name', models.CharField(max_length=100, verbose_name="Nom de l'interlocuteur / Contact")),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone')),
                ('website', models.URLField(blank=True, default='', verbose_name='Site Web')),
                ('logo_url', models.URLField(blank=True, default='', verbose_name='URL du Logo')),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('active', 'Partenaire Actif'), ('inactive', 'Inactif / Ancien Partenaire')], default='prospect', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sponsor / Partenaire',
                'verbose_name_plural': 'Sponsors & Partenaires',
                'db_table': 'finance_sponsors',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='SponsorshipPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(db_index=True, verbose_name='ID du Club')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du pack (ex: Pack Maillot Or)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix de référence HT')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description des prestations')),
                ('benefits', models.TextField(blank=True, default='', verbose_name='Contreparties (ex: Panneaux terrain, Flocage, 10 places VIP)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pack de Sponsoring',
                'verbose_name_plural': 'Packs de Sponsoring',
                'db_table': 'finance_sponsorship_packs',
            },
        ),
        migrations.CreateModel(
            name='SponsorshipContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(db_index=True, verbose_name='ID du Club')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de contrat (ex: CTR-2026-001)')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant négocié HT')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('signed', 'Signé / En cours'), ('terminated', 'Résilié'), ('expired', 'Expiré')], default='draft', max_length=10)),
                ('notes', models.TextField(blank=True, default='', verbose_name='Clauses particulières & Notes')),
                ('invoice_id', models.IntegerField(blank=True, null=True, verbose_name='ID Facture liée (invoicing)')),
                ('tax_receipt_id', models.IntegerField(blank=True, null=True, verbose_name='ID Reçu fiscal lié (tax_receipts)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='sponsors.sponsor', verbose_name='Sponsor')),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='sponsors.sponsorshippack', verbose_name='Pack lié')),
            ],
            options={
                'verbose_name': 'Contrat de Sponsoring',
                'verbose_name_plural': 'Contrats de Sponsoring',
                'db_table': 'finance_sponsorship_contracts',
                'ordering': ['-start_date'],
            },
        ),
    ]
