# Generated by Django 5.2.1 on 2026-08-28 17:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('TECHNICAL_CONTROL', 'Contrôle Technique'), ('REVISION', 'Révision'), ('REPAIR', 'Réparation'), ('INSPECTION', 'Inspection')], default='REVISION', max_length=30)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('performed_date', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Planifié'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='SCHEDULED', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='inventory.equipmentitem')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-performed_date'],
            },
        ),
    ]
