# Generated by Django 5.2.1 on 2026-08-28 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('assembly_type', models.CharField(choices=[('ORDINARY', 'Ordinaire'), ('EXTRAORDINARY', 'Extraordinaire'), ('SPECIAL', 'Spéciale')], default='ORDINARY', max_length=20)),
                ('status', models.CharField(choices=[('CONVOKED', 'Convoquée'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='CONVOKED', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('location', models.CharField(default='Siège social', max_length=255)),
                ('quorum_reached', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='AssemblyMinutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_summary', models.TextField(blank=True, default='')),
                ('signed_pv_status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING_SIGNATURE', 'En attente de signature'), ('SIGNED', 'Signé')], default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vault_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_minutes', to='vault.vaultdocument')),
                ('assembly', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='governance.generalassembly')),
            ],
        ),
        migrations.CreateModel(
            name='AssemblyConvocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocations', to='governance.generalassembly')),
            ],
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('votes_for', models.PositiveIntegerField(default=0)),
                ('votes_against', models.PositiveIntegerField(default=0)),
                ('votes_abstain', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PASSED', 'Adoptée'), ('REJECTED', 'Rejetée')], default='DRAFT', max_length=20)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='governance.generalassembly')),
            ],
        ),
    ]
