# Generated by Django 5.2.1 on 2026-08-28 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('building', models.CharField(blank=True, default='', max_length=150)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('BALLS', 'Balles & Ballons'), ('NETS', 'Filets & Poteaux'), ('APPARATUS', 'Agrès & Tapis'), ('UNIFORMS', 'Maillots & Tenues'), ('PROTECTIVE', 'Protections & Casques'), ('OTHER', 'Autre matériel')], default='OTHER', max_length=30)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('min_stock_threshold', models.PositiveIntegerField(default=5)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('LOW_STOCK', 'Stock Faible'), ('OUT_OF_STOCK', 'Rupture de stock'), ('DAMAGED', 'Endommagé')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='inventory.storagelocation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
