# Generated by Django 5.2.1 on 2026-08-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TalentProspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(db_index=True, verbose_name='ID du Club')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('birth_year', models.IntegerField(verbose_name='Année de naissance')),
                ('sport_type', models.CharField(default='football', max_length=30, verbose_name='Sport')),
                ('position', models.CharField(max_length=50, verbose_name='Poste principal')),
                ('current_club', models.CharField(blank=True, default='', max_length=150, verbose_name='Club actuel')),
                ('overall_rating', models.FloatField(default=7.5, verbose_name='Note globale (/10)')),
                ('radar_scores_json', models.JSONField(default=dict, verbose_name='Radar de compétences par critère')),
                ('status', models.CharField(choices=[('Supervisé', 'Supervisé'), ('Contacté', 'Contacté'), ('Essai Programmé', 'Essai Programmé'), ('Recruté', 'Recruté'), ('Classé', 'Classé')], default='Supervisé', max_length=30)),
                ('scout_notes', models.TextField(blank=True, default='', verbose_name='Rapport du recruteur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prospect Scouting',
                'verbose_name_plural': 'Prospects Scouting',
                'db_table': 'sport_recruitment_prospects',
                'ordering': ['-overall_rating', 'last_name'],
            },
        ),
    ]
