# Generated by Django 5.2.1 on 2026-09-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprospect',
            name='category_target',
            field=models.CharField(blank=True, default='Sénior R1', max_length=100, verbose_name='Catégorie visée'),
        ),
        migrations.AddField(
            model_name='talentprospect',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Téléphone contact'),
        ),
        migrations.AddField(
            model_name='talentprospect',
            name='height_cm',
            field=models.IntegerField(blank=True, default=185, null=True, verbose_name='Taille en cm'),
        ),
        migrations.AddField(
            model_name='talentprospect',
            name='trial_date',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name="Date d'essai"),
        ),
        migrations.AlterField(
            model_name='talentprospect',
            name='status',
            field=models.CharField(default='Prospecté', max_length=50),
        ),
    ]
