# Generated by Django 5.2.1 on 2026-09-04 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('STRIPE', 'Stripe / Carte Bancaire'), ('PAYLIB', 'PayLib'), ('PASSSPORT', "Pass'Sport"), ('MOBILE_MONEY', 'Mobile Money')], default='STRIPE', max_length=20)),
                ('transaction_id', models.CharField(db_index=True, help_text='ID externe du paiement', max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant de la transaction', max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Succès'), ('FAILED', 'Échec'), ('REFUNDED', 'Remboursé')], default='PENDING', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Payload / Réponses de la passerelle de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Transaction de paiement',
                'verbose_name_plural': 'Transactions de paiement',
                'db_table': 'shop_payment_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
