# Generated by Django 5.2.1 on 2026-08-25 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(db_index=True, verbose_name='ID du Club')),
                ('name', models.CharField(max_length=150, verbose_name="Nom de l'équipe")),
                ('sport_type', models.CharField(default='football', max_length=30, verbose_name='Sport')),
                ('category', models.CharField(default='Senior Régionale', max_length=40, verbose_name='Catégorie')),
                ('head_coach_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Entraîneur principal')),
                ('head_coach_id', models.IntegerField(blank=True, null=True, verbose_name='ID Coach IAM')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Équipe',
                'verbose_name_plural': 'Équipes',
                'db_table': 'sport_teams',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_number', models.IntegerField(blank=True, null=True, verbose_name='Numéro de maillot')),
                ('position', models.CharField(blank=True, default='', max_length=50, verbose_name='Poste principal')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='membres.member', verbose_name='Joueur')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='teams.team', verbose_name='Équipe')),
            ],
            options={
                'verbose_name': "Joueur d'équipe",
                'verbose_name_plural': "Joueurs d'équipe",
                'db_table': 'sport_team_players',
                'unique_together': {('team', 'member')},
            },
        ),
    ]
