# Generated by Django 5.2.1 on 2026-08-24 16:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Utilisée comme identifiant de connexion.', max_length=254, unique=True, verbose_name='Adresse email')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, verbose_name='Numéro de téléphone')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('is_email_verified', models.BooleanField(default=False, help_text="True si l'utilisateur a cliqué sur le lien de vérification.", verbose_name='Email vérifié')),
                ('is_2fa_enabled', models.BooleanField(default=False, help_text='Si activée, un code TOTP sera demandé à chaque connexion.', verbose_name='2FA activée')),
                ('totp_secret', models.CharField(blank=True, default='', help_text="Clé secrète générée pour l'app d'authentification (ex: Google Authenticator).", max_length=64, verbose_name='Clé secrète TOTP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'auth_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('OTHER', 'Autre')], default='', max_length=10, verbose_name='Genre')),
                ('nationality', models.CharField(blank=True, default='', max_length=60, verbose_name='Nationalité')),
                ('address_line1', models.CharField(blank=True, default='', max_length=200, verbose_name='Adresse')),
                ('address_line2', models.CharField(blank=True, default='', max_length=200, verbose_name="Complément d'adresse")),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Code postal')),
                ('country', models.CharField(blank=True, default='France', max_length=100, verbose_name='Pays')),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=100, verbose_name="Contact d'urgence (nom)")),
                ('emergency_contact_phone', models.CharField(blank=True, default='', max_length=20, verbose_name="Contact d'urgence (téléphone)")),
                ('bio', models.TextField(blank=True, default='', help_text='Courte présentation affichée sur le profil public.', verbose_name='Biographie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
                'db_table': 'auth_user_profiles',
            },
        ),
    ]
