# Generated by Django 5.2.1 on 2026-08-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sport',
            field=models.CharField(blank=True, choices=[('football', 'Football'), ('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('handball', 'Handball'), ('rugby', 'Rugby'), ('tennis', 'Tennis & Padel'), ('other', 'Autre / Général')], default='other', help_text="Sport principal pratiqué ou encadré par l'utilisateur.", max_length=30, verbose_name='Sport principal'),
        ),
    ]
