# Generated by Django 5.2.1 on 2026-08-28 14:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_contracts', '0001_initial'),
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING', 'En cours'), ('COMPLETED', 'Signé par tous'), ('CANCELLED', 'Annulé'), ('EXPIRED', 'Expiré')], default='DRAFT', max_length=20)),
                ('security_otp_enabled', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hr_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_requests', to='hr_contracts.hrcontract')),
                ('vault_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_requests', to='vault.vaultdocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Signer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('EMPLOYEE', 'Employé'), ('EMPLOYER', 'Employeur'), ('AGENT', 'Agent / Représentant'), ('WITNESS', 'Témoin')], default='EMPLOYEE', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SIGNED', 'Signé'), ('DECLINED', 'Refusé')], default='PENDING', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('otp_code', models.CharField(blank=True, default='', max_length=10)),
                ('signature_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('signature_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='signatures.signaturerequest')),
            ],
        ),
    ]
