# Generated by Django 5.2.1 on 2026-08-25 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membres', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent_name', models.CharField(max_length=150, verbose_name='Adversaire')),
                ('is_home', models.BooleanField(default=True, verbose_name='Match à domicile')),
                ('match_date', models.DateTimeField(verbose_name='Date et heure du match')),
                ('venue', models.CharField(blank=True, default='', max_length=200, verbose_name='Lieu / Gymnase / Stade')),
                ('score_home', models.IntegerField(blank=True, null=True, verbose_name='Score Domicile')),
                ('score_away', models.IntegerField(blank=True, null=True, verbose_name='Score Extérieur')),
                ('status', models.CharField(choices=[('A venir', 'À venir'), ('En cours', 'En cours'), ('Terminé', 'Terminé'), ('Reporté', 'Reporté'), ('Annulé', 'Annulé')], default='A venir', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='teams.team', verbose_name='Équipe')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matchs',
                'db_table': 'sport_matches',
                'ordering': ['-match_date'],
            },
        ),
        migrations.CreateModel(
            name='Callup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Convoqué', 'Convoqué'), ('Présent', 'Présent'), ('Absent', 'Absent'), ('Excusé', 'Excusé')], default='Convoqué', max_length=30)),
                ('notes', models.CharField(blank=True, default='', max_length=200, verbose_name='Remarques convocation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callups', to='membres.member', verbose_name='Joueur')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callups', to='competitions.matchevent', verbose_name='Match')),
            ],
            options={
                'verbose_name': 'Convocation',
                'verbose_name_plural': 'Convocations',
                'db_table': 'sport_callups',
                'unique_together': {('match', 'member')},
            },
        ),
        migrations.CreateModel(
            name='MatchPlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Points / Buts')),
                ('assists', models.IntegerField(default=0, verbose_name='Passes décisives')),
                ('rebounds', models.IntegerField(default=0, verbose_name='Rebonds / Arrêts')),
                ('fouls', models.IntegerField(default=0, verbose_name='Fautes / Cartons')),
                ('rating', models.FloatField(default=7.0, verbose_name='Note du match (/10)')),
                ('is_mvp', models.BooleanField(default=False, verbose_name='Joueur du match (MVP)')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='competitions.matchevent', verbose_name='Match')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='membres.member', verbose_name='Joueur')),
            ],
            options={
                'verbose_name': 'Statistique Joueur Match',
                'verbose_name_plural': 'Statistiques Joueurs Match',
                'db_table': 'sport_match_player_stats',
                'unique_together': {('match', 'member')},
            },
        ),
    ]
