# Generated by Django 5.2.1 on 2026-10-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchevent',
            name='coach_debrief',
            field=models.TextField(blank=True, default='', verbose_name='Débriefing / Bilan du Coach'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='mvp_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='MVP Désigné'),
        ),
    ]
