# Generated by Django 5.2.1 on 2026-09-04 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.BigIntegerField(db_index=True, help_text='ID du club propriétaire')),
                ('name', models.CharField(help_text='Nom de la catégorie', max_length=100)),
                ('slug', models.SlugField(help_text='Slug URL unique pour le club', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Catégorie parente si sous-catégorie', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Catégorie produit',
                'verbose_name_plural': 'Catégories produits',
                'db_table': 'shop_categories',
                'ordering': ['name'],
                'unique_together': {('club_id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.BigIntegerField(db_index=True, help_text='ID du club propriétaire')),
                ('name', models.CharField(help_text='Nom du produit', max_length=255)),
                ('slug', models.SlugField(help_text='Slug URL unique pour le club', max_length=280)),
                ('description', models.TextField(blank=True, default='')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Prix de base', max_digits=10)),
                ('currency', models.CharField(default='EUR', help_text='Devise (EUR, XAF, USD)', max_length=10)),
                ('main_image_url', models.URLField(blank=True, help_text='Image principale', max_length=1000, null=True)),
                ('images_gallery', models.JSONField(blank=True, default=list, help_text="Liste d'URLs d'images secondaires")),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié'), ('OUT_OF_STOCK', 'Rupture de stock'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=20)),
                ('is_customizable', models.BooleanField(default=False, help_text='Autorise le flocage (Nom, Numéro)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Catégorie associée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'db_table': 'shop_products',
                'ordering': ['-created_at'],
                'unique_together': {('club_id', 'slug')},
            },
        ),
    ]
